"""Esquema inicial completo

Revision ID: 6b7334131575
Revises: 
Create Date: 2026-07-13 20:29:08.847508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7334131575'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('intentos_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_intentado', sa.String(length=180), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('motivo_fallo', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intentos_login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intentos_login_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_intentos_login_email_intentado'), ['email_intentado'], unique=False)
        batch_op.create_index(batch_op.f('ix_intentos_login_ip'), ['ip'], unique=False)

    op.create_table('newsletter_suscriptores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('token_confirmacion', sa.String(length=64), nullable=True),
    sa.Column('suscrito_en', sa.DateTime(), nullable=False),
    sa.Column('dado_de_baja_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletter_suscriptores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_suscriptores_email'), ['email'], unique=True)

    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('portafolio_proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cliente', sa.String(length=160), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('imagen_portada', sa.String(length=255), nullable=True),
    sa.Column('tecnologias', sa.String(length=255), nullable=True),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('publicado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('portafolio_proyectos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portafolio_proyectos_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_portafolio_proyectos_publicado'), ['publicado'], unique=False)

    op.create_table('preguntas_frecuentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(length=255), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preguntas_frecuentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preguntas_frecuentes_activo'), ['activo'], unique=False)

    op.create_table('rangos_presupuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('etiqueta', sa.String(length=120), nullable=False),
    sa.Column('monto_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    with op.batch_alter_table('rangos_presupuesto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rangos_presupuesto_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_rangos_presupuesto_creado_en'), ['creado_en'], unique=False)

    op.create_table('rate_limit_violaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('limite_excedido', sa.String(length=40), nullable=False),
    sa.Column('num_solicitudes', sa.Integer(), nullable=False),
    sa.Column('ventana_inicio', sa.DateTime(), nullable=False),
    sa.Column('ventana_fin', sa.DateTime(), nullable=False),
    sa.Column('resulto_en_bloqueo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limit_violaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_violaciones_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_violaciones_ip'), ['ip'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_creado_en'), ['creado_en'], unique=False)

    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_desde', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicios_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_servicios_creado_en'), ['creado_en'], unique=False)

    op.create_table('testimonios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=120), nullable=False),
    sa.Column('empresa', sa.String(length=120), nullable=True),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint('calificacion IS NULL OR (calificacion BETWEEN 1 AND 5)', name='ck_testimonio_calificacion'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testimonios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_testimonios_aprobado'), ['aprobado'], unique=False)
        batch_op.create_index(batch_op.f('ix_testimonios_creado_en'), ['creado_en'], unique=False)

    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=64), nullable=True),
    sa.Column('two_factor_habilitado', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administradores_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_administradores_email'), ['email'], unique=True)

    op.create_table('portafolio_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['portafolio_proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('admin_2fa_codigos_respaldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administrador_id', sa.Integer(), nullable=False),
    sa.Column('codigo_hash', sa.String(length=64), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administrador_id'], ['administradores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_2fa_codigos_respaldo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_2fa_codigos_respaldo_administrador_id'), ['administrador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_2fa_codigos_respaldo_creado_en'), ['creado_en'], unique=False)

    op.create_table('archivos_adjuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('nombre_almacenado', sa.String(length=255), nullable=False),
    sa.Column('ruta_o_url', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('entidad_tipo', sa.String(length=40), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('subido_por_admin_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subido_por_admin_id'], ['administradores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archivos_adjuntos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archivos_adjuntos_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_archivos_adjuntos_entidad_id'), ['entidad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_archivos_adjuntos_entidad_tipo'), ['entidad_tipo'], unique=False)

    op.create_table('bitacora_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=60), nullable=False),
    sa.Column('nivel', sa.Enum('info', 'warning', 'error', 'critical', name='bitacora_nivel'), nullable=False),
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administrador_id'], ['administradores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bitacora_eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bitacora_eventos_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_bitacora_eventos_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_bitacora_eventos_tipo_evento'), ['tipo_evento'], unique=False)

    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('resumen', sa.String(length=500), nullable=True),
    sa.Column('contenido_html', sa.Text(), nullable=False),
    sa.Column('imagen_portada', sa.String(length=255), nullable=True),
    sa.Column('autor_admin_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('articulo', 'noticia', name='blog_tipo'), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'publicado', name='blog_estado'), nullable=False),
    sa.Column('publicado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_admin_id'], ['administradores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_tipo'), ['tipo'], unique=False)

    op.create_table('configuracion_sitio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('texto', 'numero', 'booleano', 'json', name='config_tipo'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_por_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_admin_id'], ['administradores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    with op.batch_alter_table('configuracion_sitio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracion_sitio_categoria'), ['categoria'], unique=False)

    op.create_table('contactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('empresa', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('rango_presupuesto_id', sa.Integer(), nullable=True),
    sa.Column('descripcion_proyecto', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('nuevo', 'en_seguimiento', 'cotizado', 'ganado', 'perdido', 'descartado', name='contacto_estado'), nullable=False),
    sa.Column('observaciones_internas', sa.Text(), nullable=True),
    sa.Column('fecha_seguimiento', sa.Date(), nullable=True),
    sa.Column('administrador_asignado_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administrador_asignado_id'], ['administradores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rango_presupuesto_id'], ['rangos_presupuesto.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contactos_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_contactos_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contactos_estado'), ['estado'], unique=False)

    op.create_table('lista_negra_ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('bloqueado_en', sa.DateTime(), nullable=False),
    sa.Column('bloqueo_permanente', sa.Boolean(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por_admin_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_admin_id'], ['administradores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lista_negra_ip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lista_negra_ip_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_lista_negra_ip_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_lista_negra_ip_ip'), ['ip'], unique=True)

    op.create_table('sesiones_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administrador_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('revocada', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administrador_id'], ['administradores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sesiones_admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_admin_administrador_id'), ['administrador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sesiones_admin_creado_en'), ['creado_en'], unique=False)

    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('password_reset', 'email_verification', name='token_tipo'), nullable=False),
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('ip_solicitante', sa.String(length=45), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administrador_id'], ['administradores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_administrador_id'), ['administrador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_creado_en'), ['creado_en'], unique=False)

    op.create_table('blog_post_categorias',
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('blog_categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_categoria_id'], ['blog_categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_post_id', 'blog_categoria_id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('empresa', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_desde_contacto_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_desde_contacto_id'], ['contactos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_email'), ['email'], unique=False)

    op.create_table('correos_enviados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinatario', sa.String(length=180), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('notificacion_admin', 'confirmacion_cliente', 'password_reset', 'otro', name='correo_tipo'), nullable=False),
    sa.Column('contacto_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('enviado', 'fallido', 'pendiente', name='correo_estado'), nullable=False),
    sa.Column('error_detalle', sa.Text(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correos_enviados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correos_enviados_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_correos_enviados_estado'), ['estado'], unique=False)

    op.create_table('chat_conversaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contacto_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('canal', sa.Enum('web', 'whatsapp', name='chat_canal'), nullable=False),
    sa.Column('iniciado_en', sa.DateTime(), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contacto_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'enviada', 'aceptada', 'rechazada', 'expirada', name='cotizacion_estado'), nullable=False),
    sa.Column('valida_hasta', sa.Date(), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('creado_por_admin_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_admin_id'], ['administradores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotizaciones_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_cotizaciones_estado'), ['estado'], unique=False)

    op.create_table('proyectos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('propuesta', 'en_progreso', 'completado', 'cancelado', name='proyecto_estado'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin_estimada', sa.Date(), nullable=True),
    sa.Column('fecha_fin_real', sa.Date(), nullable=True),
    sa.Column('monto_acordado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proyectos_cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proyectos_cliente_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proyectos_cliente_creado_en'), ['creado_en'], unique=False)

    op.create_table('reuniones_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('contacto_id', sa.Integer(), nullable=True),
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(), nullable=True),
    sa.Column('ubicacion_o_link', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('programada', 'confirmada', 'cancelada', 'completada', name='reunion_estado'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administrador_id'], ['administradores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reuniones_agenda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reuniones_agenda_creado_en'), ['creado_en'], unique=False)

    op.create_table('tickets_soporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('contacto_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('abierto', 'en_progreso', 'resuelto', 'cerrado', name='ticket_estado'), nullable=False),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', 'urgente', name='ticket_prioridad'), nullable=False),
    sa.Column('asignado_admin_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_admin_id'], ['administradores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets_soporte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_soporte_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_soporte_estado'), ['estado'], unique=False)

    op.create_table('chat_mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=False),
    sa.Column('remitente_tipo', sa.Enum('visitante', 'admin', 'bot', name='chat_remitente_tipo'), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['chat_conversaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_mensajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_mensajes_conversacion_id'), ['conversacion_id'], unique=False)

    op.create_table('ticket_mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('autor_tipo', sa.Enum('cliente', 'admin', name='ticket_autor_tipo'), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_soporte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_mensajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_mensajes_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_mensajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_mensajes_ticket_id'))

    op.drop_table('ticket_mensajes')
    with op.batch_alter_table('chat_mensajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_mensajes_conversacion_id'))

    op.drop_table('chat_mensajes')
    with op.batch_alter_table('tickets_soporte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_soporte_estado'))
        batch_op.drop_index(batch_op.f('ix_tickets_soporte_creado_en'))

    op.drop_table('tickets_soporte')
    with op.batch_alter_table('reuniones_agenda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reuniones_agenda_creado_en'))

    op.drop_table('reuniones_agenda')
    with op.batch_alter_table('proyectos_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proyectos_cliente_creado_en'))
        batch_op.drop_index(batch_op.f('ix_proyectos_cliente_cliente_id'))

    op.drop_table('proyectos_cliente')
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cotizaciones_estado'))
        batch_op.drop_index(batch_op.f('ix_cotizaciones_creado_en'))

    op.drop_table('cotizaciones')
    op.drop_table('chat_conversaciones')
    with op.batch_alter_table('correos_enviados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correos_enviados_estado'))
        batch_op.drop_index(batch_op.f('ix_correos_enviados_creado_en'))

    op.drop_table('correos_enviados')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_email'))
        batch_op.drop_index(batch_op.f('ix_clientes_creado_en'))

    op.drop_table('clientes')
    op.drop_table('blog_post_categorias')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_creado_en'))
        batch_op.drop_index(batch_op.f('ix_tokens_administrador_id'))

    op.drop_table('tokens')
    with op.batch_alter_table('sesiones_admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_admin_creado_en'))
        batch_op.drop_index(batch_op.f('ix_sesiones_admin_administrador_id'))

    op.drop_table('sesiones_admin')
    with op.batch_alter_table('lista_negra_ip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lista_negra_ip_ip'))
        batch_op.drop_index(batch_op.f('ix_lista_negra_ip_creado_en'))
        batch_op.drop_index(batch_op.f('ix_lista_negra_ip_activo'))

    op.drop_table('lista_negra_ip')
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contactos_estado'))
        batch_op.drop_index(batch_op.f('ix_contactos_email'))
        batch_op.drop_index(batch_op.f('ix_contactos_creado_en'))

    op.drop_table('contactos')
    with op.batch_alter_table('configuracion_sitio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracion_sitio_categoria'))

    op.drop_table('configuracion_sitio')
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_tipo'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_estado'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_creado_en'))

    op.drop_table('blog_posts')
    with op.batch_alter_table('bitacora_eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bitacora_eventos_tipo_evento'))
        batch_op.drop_index(batch_op.f('ix_bitacora_eventos_ip'))
        batch_op.drop_index(batch_op.f('ix_bitacora_eventos_creado_en'))

    op.drop_table('bitacora_eventos')
    with op.batch_alter_table('archivos_adjuntos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archivos_adjuntos_entidad_tipo'))
        batch_op.drop_index(batch_op.f('ix_archivos_adjuntos_entidad_id'))
        batch_op.drop_index(batch_op.f('ix_archivos_adjuntos_creado_en'))

    op.drop_table('archivos_adjuntos')
    with op.batch_alter_table('admin_2fa_codigos_respaldo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_2fa_codigos_respaldo_creado_en'))
        batch_op.drop_index(batch_op.f('ix_admin_2fa_codigos_respaldo_administrador_id'))

    op.drop_table('admin_2fa_codigos_respaldo')
    op.drop_table('rol_permisos')
    op.drop_table('portafolio_imagenes')
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administradores_email'))
        batch_op.drop_index(batch_op.f('ix_administradores_creado_en'))

    op.drop_table('administradores')
    with op.batch_alter_table('testimonios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_testimonios_creado_en'))
        batch_op.drop_index(batch_op.f('ix_testimonios_aprobado'))

    op.drop_table('testimonios')
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicios_creado_en'))
        batch_op.drop_index(batch_op.f('ix_servicios_activo'))

    op.drop_table('servicios')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_creado_en'))

    op.drop_table('roles')
    with op.batch_alter_table('rate_limit_violaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_violaciones_ip'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_violaciones_creado_en'))

    op.drop_table('rate_limit_violaciones')
    with op.batch_alter_table('rangos_presupuesto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rangos_presupuesto_creado_en'))
        batch_op.drop_index(batch_op.f('ix_rangos_presupuesto_activo'))

    op.drop_table('rangos_presupuesto')
    with op.batch_alter_table('preguntas_frecuentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preguntas_frecuentes_activo'))

    op.drop_table('preguntas_frecuentes')
    with op.batch_alter_table('portafolio_proyectos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portafolio_proyectos_publicado'))
        batch_op.drop_index(batch_op.f('ix_portafolio_proyectos_creado_en'))

    op.drop_table('portafolio_proyectos')
    op.drop_table('permisos')
    with op.batch_alter_table('newsletter_suscriptores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_suscriptores_email'))

    op.drop_table('newsletter_suscriptores')
    with op.batch_alter_table('intentos_login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intentos_login_ip'))
        batch_op.drop_index(batch_op.f('ix_intentos_login_email_intentado'))
        batch_op.drop_index(batch_op.f('ix_intentos_login_creado_en'))

    op.drop_table('intentos_login')
    op.drop_table('blog_categorias')
    # ### end Alembic commands ###
